---
# build os/arch for gox
build:
  - darwin/amd64
  - darwin/arm64
  - linux/386
  - linux/amd64
  - linux/arm
  - windows/amd64
  - freebsd/amd64
  # doesn't compile
  #- android/arm

target: docopts

releases:
  # yaml keys must match the git tag
  ##################################

  v0.6.4-with-no-mangle-double-dash:
    name: bug fix v0.6.4-with-no-mangle-double-dash
    description: |
      This is a bug fix release.

      features changes:
        - fix error refusing mangling double dash in global mode [#52]
        - still refuse to mangle single dash `[-]` in global mode (not compatible with v0.6.1)
        - now can mangle single-dash and double-dash in `-G` mode
        - fix output bash empty array #53

      internal changes:
        - use Go 1.17.1 for compiling
        - `language_agnostic_tester.py` re-write for python3
        - sort argument key in `Print_bash_args()` `Print_bash_global()`
        - sort input keys in `docopts_test.go`
        - add PR #52 test to `testcases.docopt`
        - completed developper's documentation
        - #52 ignore `[--]` double-dash option in `Print_bash_global()`
        - reformat of Go code with gofmt indent change Space ==> Tab
        - add `tests/functional_tests_docopts.bats`

  v0.6.3-rc2:
    name: "docopts binary transitional v0.6.3-rc2"
    description: |
      This is a transitional release.

      It supports all the previous command line API plus some extra options.
      Fully compatible with previous 0.6.2 python code for Bash.
      See: https://github.com/docopt/docopts/tree/v0.6.1%2Bfix

      based on master branch

      features changes:
        - `docopts.sh` function `docopt_get_help_string()` now uses awk to extract only first `Usage:`

      internal changes:
        - use Go 1.14 for compiling
        - more pre-built binaries, removed darwin/386
        - fixed #44 `get_docopts.sh` for MACOS + functionnal tests
        - removed bats git submodule
        - use [bats-core 1.2-dev](https://github.com/bats-core/bats-core) as testing framework from travis
        - `deploy.sh` removed, now use its [own repository](https://github.com/opensource-expert/deploy.sh)
        - updated Makefile to use `get_ldflags.sh` from `deploy.sh`
        - [travis hack](travis/get_bash5_macos.sh) to get faster build on macos with our embedded bash5 binary

  v0.6.3-rc1:
    name: "docopts binary transitional v0.6.3-rc1"
    description: |
      This is a transitional release.

      It supports all the previous API plus some extra command line options.
      Fully compatible with previous 0.6.2 python code for Bash.
      See: https://github.com/docopt/docopts/tree/v0.6.1%2Bfix

      based on master branch

      changes:
        - more test for MACOS
        - bash 3.2 support is more documented and fixed
        - use bats-core as testing framework
        - updated README merged from old README.rst
        - now documentation introduce `docopts.sh` See [docs](https://github.com/docopt/docopts/tree/v0.6.3-rc1/docs/)
        - added Makefile
        - added build_doc.sh PoC markdown preprocessor

      all examples written for docopts:
        - shebang conversion `#!/bin/bash` ==> `#!/usr/bin/env bash`
        - legacy example completed
        - example from README extracted a file, and merged in README via build_doc.sh
        - sshdiff full example coded
        - added examples with `--auto -G`

      docopts.sh helper:
        - is more documented in the code
        - as a documenation in [docs/README.md](https://github.com/docopt/docopts/tree/v0.6.3-rc1/docs/README.md)
        - now supports bash strict mode (`set -euo pipefail`)
        - now supports `--auto -G` to auto parse with global vars (doesn't use bash 4 associative array)

      `docopts` behavior sould be unchanged:
        - add mangled name collision detection

  v0.6.3-alpha1:
    name: "docopts for Bash first release in golang"
    description: |
      This is a transitional release. It is a complete rewrite of the python's code in go.
      It supports all the previous API plus some extra command line options.

      Fully compatible with previous 0.6.2 python code for Bash.

      based on https://github.com/docopt/docopts/tree/packaging-debian

  v0.6.2:
    name: "first release in Go"
    description: |
      This is a transitional release.

      Dopopt for shell.

      It supports all the previous API.
      Fully compatible with previous 0.6.1 python code for Bash.
      See: https://github.com/docopt/docopts/tree/v0.6.1%2Bfix

      based on master branch

      changes:
        - now written in Go, no more python dependancy

